SUPABASE_URL=https://srhaytajyfrniuvnkfpd.supabase.co
SUPABASE_PUBLISHABLE_KEY=sb_publishable_CJavqYCusEBD7cIebhH5tQ_K_I9AXpE
SENTRY_DSN=https://7551f3236520b84b27ec473a1d7c1480@o60909.ingest.us.sentry.io/4511233545011200
GOOGLE_OAUTH_CLIENT_ID=
APPLE_SERVICE_ID=
